version: '3'
services:
  mysql:
    container_name: sql-1
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-exampleVolume:/var/lib/mysql
volumes:
  db-exampleVolume: